# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "53ed2a2c5ae0b906d8dbaff45f016c30"
name = "brock"
handle = "brock-1"
application_url = "https://leonard-local-spot-optimization.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-c0eb237e.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://leonard-local-spot-optimization.trycloudflare.com/auth/callback",
  "https://leonard-local-spot-optimization.trycloudflare.com/auth/shopify/callback",
  "https://leonard-local-spot-optimization.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
